CREATE TABLE projects (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(32) NOT NULL,
	owner_id INTEGER REFERENCES users(id) NOT NULL
);

CREATE TABLE tasks (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name VARCHAR(32) NOT NULL,
	project_id INTEGER REFERENCES projects(id) NOT NULL,
	assignee_id INTEGER REFERENCES users(id)
);