name: "build nix"

on: ["push", "pull_request"]

jobs:
  build-nix:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v3"
    - uses: "cachix/install-nix-action@v18"
    - run: "nix build"
